/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './localStorage.module';
import * as import2 from '@angular/common';
import * as import3 from './localStorage.service';
class AngularxLocalStorageInjector extends import0.ɵNgModuleInjector<import1.AngularxLocalStorage> {
  _CommonModule_0:import2.CommonModule;
  _AngularxLocalStorage_1:import1.AngularxLocalStorage;
  __NgLocalization_2:import2.NgLocaleLocalization;
  __LocalStorage_3:import3.LocalStorage;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_2():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_2 == null)) { (this.__NgLocalization_2 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_2;
  }
  get _LocalStorage_3():import3.LocalStorage {
    if ((this.__LocalStorage_3 == null)) { (this.__LocalStorage_3 = new import3.LocalStorage()); }
    return this.__LocalStorage_3;
  }
  createInternal():import1.AngularxLocalStorage {
    this._CommonModule_0 = new import2.CommonModule();
    this._AngularxLocalStorage_1 = new import1.AngularxLocalStorage();
    return this._AngularxLocalStorage_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import1.AngularxLocalStorage)) { return this._AngularxLocalStorage_1; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_2; }
    if ((token === import3.LocalStorage)) { return this._LocalStorage_3; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const AngularxLocalStorageNgFactory:import0.NgModuleFactory<import1.AngularxLocalStorage> = new import0.NgModuleFactory<any>(AngularxLocalStorageInjector,import1.AngularxLocalStorage);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRTovV09SS0lOR19EaXIvbnBtUHJvamVjdHMvbG9jYWxTdG9yYWdlL2xvY2FsU3RvcmFnZS5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRTovV09SS0lOR19EaXIvbnBtUHJvamVjdHMvbG9jYWxTdG9yYWdlL2xvY2FsU3RvcmFnZS5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
